disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Vale's Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
  name = "Valentin B."
  email = "valentin.be@protonmail.com"
  headline = "I like all things low-level"
  links = [
   { email = "mailto:valentin.be@protonmail.com" },
   { github = "https://github.com/vbe0201" },
  ]

description = "A place where I share knowledge, thoughts and opinions"
